// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpiamxEc-mhxCn744Jx7PUBAf1-CUPvQ',
    appId: '1:264589086182:web:36a67eb3ecf59d22ccda27',
    messagingSenderId: '264589086182',
    projectId: 'twitterclone-83a5b',
    authDomain: 'twitterclone-83a5b.firebaseapp.com',
    storageBucket: 'twitterclone-83a5b.appspot.com',
    measurementId: 'G-228CF9NBY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVjhrWUz8vYwaaLLNLStsLX5kQ_9TWbu4',
    appId: '1:264589086182:android:613d1d548837248eccda27',
    messagingSenderId: '264589086182',
    projectId: 'twitterclone-83a5b',
    storageBucket: 'twitterclone-83a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6uyvdLnJEWq1rd1yBBEpIIOgT-m51PY',
    appId: '1:264589086182:ios:eab86e252f05d27bccda27',
    messagingSenderId: '264589086182',
    projectId: 'twitterclone-83a5b',
    storageBucket: 'twitterclone-83a5b.appspot.com',
    iosClientId: '264589086182-0iu3cglkvi9qckf8h83fbm2tet0e2tlj.apps.googleusercontent.com',
    iosBundleId: 'com.cal.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz6uyvdLnJEWq1rd1yBBEpIIOgT-m51PY',
    appId: '1:264589086182:ios:81cfe5957b36842eccda27',
    messagingSenderId: '264589086182',
    projectId: 'twitterclone-83a5b',
    storageBucket: 'twitterclone-83a5b.appspot.com',
    iosClientId: '264589086182-bmh3g1feuvsok8abrov45bm8i8hj5atf.apps.googleusercontent.com',
    iosBundleId: 'com.cal.twitterclone.RunnerTests',
  );
}
